title: "A G Adeeth Cariappa"
author: "A G Adeeth Cariappa"
description: "ICAR - National Dairy Research Institute"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true          # show site description and social links in the footer
show_excerpts: false        # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:
  - {title: "CV", url: "/katie.pdf", icon: home}
  - {title: "Lab", url: "https://childlanglab.com"}
  - {title: "Blog", file: "blog.md"}

external:                  # see http://fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:kathryn.schuler@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/kschuler"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/kathrynschuler"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
